### ISSUE TITLE
rvm compatible ruby-version file

### ISSUE THREAD

**Issue by Lewiscowles1986** [baweaver/matchable#1]
👋 Interesting library.

I Know you have documented this in the README.md, but I was wondering how you would feel about a tiny PR to create a `.ruby-version` file. Environments such as [RVM](https://rvm.io) can then auto-switch for developers using multiple Ruby runtimes.

**Comment by baweaver** [comment]
Resolved by https://github.com/baweaver/matchable/commit/cbb281212c890afc330ec6a411cd4beaf36463d6
